CREATE TABLE COUNTRIES
(
  COUNTRY_ID CHAR(3) NOT NULL,
  COUNTRY_NAME VARCHAR(60) NOT NULL,
  CONTINENT CHAR(13) NOT NULL,
  COUNTRY_STATUS CHAR(6) NOT NULL,
  ADMISSION_DATE DATE,
  PRIMARY KEY (COUNTRY_ID)
);

CREATE TABLE REPRESENTATIVES
(
  REP_ID CHAR(7) NOT NULL,
  COUNTRY_ID CHAR(3) NOT NULL,
  REP_NAME VARCHAR(60) NOT NULL,
  TITLE VARCHAR(100) NOT NULL,
  REP_STATUS CHAR(6) NOT NULL,
  ACTIVE_DATE DATE,
  INACTIVE_DATE DATE,
  PRIMARY KEY (REP_ID)
);

CREATE TABLE SUBSIDIARIES
(
  COMMITTEE_ID CHAR(6) NOT NULL,
  COMMITTEE_NAME VARCHAR(60) NOT NULL,
  COUNTRY_ID CHAR(3) NOT NULL,
  COMMITTEE_STATUS CHAR(6) NOT NULL,
  ACTIVE_DATE DATE,
  INACTIVE_DATE DATE,
  PRIMARY KEY (COMMITTEE_ID)
)



